FROM openjdk:17-alpine
VOLUME /tmp
COPY target/projects-microservice-0.0.1-SNAPSHOT.jar projects-microservice.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/projects-microservice.jar"]

